#########################################################################################
# TABLE OF CONTENT

#  default_config
#  lovelace
#  tts
#  inclusions
#  shopping list

#########################################################################################

#  default config of homeassistant
default_config:

#  Home Assistant dashboard -> ui-lovelace.yaml
lovelace:
  mode: yaml

#  tts (Text to speech) 
tts:
  - platform: google_translate

#  inclusions
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#  shopping list
#  is included over frontend (Integrations > Configuration > Discovered)
#  shopping_list: