#########################################################################################
# TABLE OF CONTENT
#
#  config
#  lovelace (Dashboard)
#  tts  (text to speech)
#  inclusions
#     group: 
#     automation:
#     script:
#     scene:
#
#########################################################################################

#  config of homeassistant
config:

#  Home Assistant dashboards -> ui-lovelace.yaml
lovelace:
  mode: yaml
  # added custom dashboards at custom_components/lovelace/dashboards.yaml
  dashboards: !include custom_components/lovelace/dashboards.yaml

#  tts (Text to speech) 
tts:
  - platform: google_translate

#  inclusions
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
