# file contains: (diese datei ist obligatorisch)

# Title of dashboard
title: Overview

# tabs
views:
  # tab overview
  - title: overview
    path: overview # Unique path for direct access /lovelace/${path}
    cards:
      # card light
      - type: light
        entity: light.moodlite
      # gernerated cards
      # card weather
      - type: weather-forecast
        entity: weather.home
      # card calendar
      - type: calendar
        entities: 
        - calendar.calendar_1
      # card text
      - type: markdown
        title: Lovelace
        content: >
          Notiz Block.
